// Code generated by protoc-gen-go.
// source: gmaj.proto
// DO NOT EDIT!

/*
Package gmajpb is a generated protocol buffer package.

It is generated from these files:
	gmaj.proto

It has these top-level messages:
	Node
	TransferKeysReq
	MT
	KeyVal
	ID
	Key
	Val
*/
package gmajpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Node contains a node ID and address.
type Node struct {
	Id   []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Node) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Node) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type TransferKeysReq struct {
	FromId []byte `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToNode *Node  `protobuf:"bytes,2,opt,name=to_node,json=toNode" json:"to_node,omitempty"`
}

func (m *TransferKeysReq) Reset()                    { *m = TransferKeysReq{} }
func (m *TransferKeysReq) String() string            { return proto.CompactTextString(m) }
func (*TransferKeysReq) ProtoMessage()               {}
func (*TransferKeysReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransferKeysReq) GetFromId() []byte {
	if m != nil {
		return m.FromId
	}
	return nil
}

func (m *TransferKeysReq) GetToNode() *Node {
	if m != nil {
		return m.ToNode
	}
	return nil
}

type MT struct {
}

func (m *MT) Reset()                    { *m = MT{} }
func (m *MT) String() string            { return proto.CompactTextString(m) }
func (*MT) ProtoMessage()               {}
func (*MT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type KeyVal struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
}

func (m *KeyVal) Reset()                    { *m = KeyVal{} }
func (m *KeyVal) String() string            { return proto.CompactTextString(m) }
func (*KeyVal) ProtoMessage()               {}
func (*KeyVal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *KeyVal) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyVal) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type ID struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *ID) Reset()                    { *m = ID{} }
func (m *ID) String() string            { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()               {}
func (*ID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ID) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type Key struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Val struct {
	Val string `protobuf:"bytes,1,opt,name=val" json:"val,omitempty"`
}

func (m *Val) Reset()                    { *m = Val{} }
func (m *Val) String() string            { return proto.CompactTextString(m) }
func (*Val) ProtoMessage()               {}
func (*Val) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Val) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

func init() {
	proto.RegisterType((*Node)(nil), "gmajpb.Node")
	proto.RegisterType((*TransferKeysReq)(nil), "gmajpb.TransferKeysReq")
	proto.RegisterType((*MT)(nil), "gmajpb.MT")
	proto.RegisterType((*KeyVal)(nil), "gmajpb.KeyVal")
	proto.RegisterType((*ID)(nil), "gmajpb.ID")
	proto.RegisterType((*Key)(nil), "gmajpb.Key")
	proto.RegisterType((*Val)(nil), "gmajpb.Val")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Chord service

type ChordClient interface {
	// GetPredecessor returns the node believed to be the current predecessor.
	GetPredecessor(ctx context.Context, in *MT, opts ...grpc.CallOption) (*Node, error)
	// GetSuccessor returns the node believed to be the current successor.
	GetSuccessor(ctx context.Context, in *MT, opts ...grpc.CallOption) (*Node, error)
	// SetPredecessor sets Node as the predeccessor. This function does not do
	// any validation.
	SetPredecessor(ctx context.Context, in *Node, opts ...grpc.CallOption) (*MT, error)
	// SetPredecessor sets Node as the successor. This function does not do any
	// validation.
	SetSuccessor(ctx context.Context, in *Node, opts ...grpc.CallOption) (*MT, error)
	// Notify notifies Chord that Node thinks it is our predecessor. This has
	// the potential to initiate the transferring of keys.
	Notify(ctx context.Context, in *Node, opts ...grpc.CallOption) (*MT, error)
	// ClosestPrecedingFinger returns the entry of the finger table that
	// precedes ID but is closest to it.
	ClosestPrecedingFinger(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Node, error)
	// FindSuccessor finds the node the succedes ID. May initiate RPC calls to
	// other nodes.
	FindSuccessor(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Node, error)
	// Get returns the value in Chord ring for the given key.
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Val, error)
	// Put writes a key value pair to the Chord ring.
	Put(ctx context.Context, in *KeyVal, opts ...grpc.CallOption) (*MT, error)
	// TransferKeys tells a node to transfer keys in a specified range to
	// another node.
	TransferKeys(ctx context.Context, in *TransferKeysReq, opts ...grpc.CallOption) (*MT, error)
}

type chordClient struct {
	cc *grpc.ClientConn
}

func NewChordClient(cc *grpc.ClientConn) ChordClient {
	return &chordClient{cc}
}

func (c *chordClient) GetPredecessor(ctx context.Context, in *MT, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := grpc.Invoke(ctx, "/gmajpb.Chord/GetPredecessor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) GetSuccessor(ctx context.Context, in *MT, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := grpc.Invoke(ctx, "/gmajpb.Chord/GetSuccessor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) SetPredecessor(ctx context.Context, in *Node, opts ...grpc.CallOption) (*MT, error) {
	out := new(MT)
	err := grpc.Invoke(ctx, "/gmajpb.Chord/SetPredecessor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) SetSuccessor(ctx context.Context, in *Node, opts ...grpc.CallOption) (*MT, error) {
	out := new(MT)
	err := grpc.Invoke(ctx, "/gmajpb.Chord/SetSuccessor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) Notify(ctx context.Context, in *Node, opts ...grpc.CallOption) (*MT, error) {
	out := new(MT)
	err := grpc.Invoke(ctx, "/gmajpb.Chord/Notify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) ClosestPrecedingFinger(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := grpc.Invoke(ctx, "/gmajpb.Chord/ClosestPrecedingFinger", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) FindSuccessor(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := grpc.Invoke(ctx, "/gmajpb.Chord/FindSuccessor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Val, error) {
	out := new(Val)
	err := grpc.Invoke(ctx, "/gmajpb.Chord/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) Put(ctx context.Context, in *KeyVal, opts ...grpc.CallOption) (*MT, error) {
	out := new(MT)
	err := grpc.Invoke(ctx, "/gmajpb.Chord/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) TransferKeys(ctx context.Context, in *TransferKeysReq, opts ...grpc.CallOption) (*MT, error) {
	out := new(MT)
	err := grpc.Invoke(ctx, "/gmajpb.Chord/TransferKeys", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Chord service

type ChordServer interface {
	// GetPredecessor returns the node believed to be the current predecessor.
	GetPredecessor(context.Context, *MT) (*Node, error)
	// GetSuccessor returns the node believed to be the current successor.
	GetSuccessor(context.Context, *MT) (*Node, error)
	// SetPredecessor sets Node as the predeccessor. This function does not do
	// any validation.
	SetPredecessor(context.Context, *Node) (*MT, error)
	// SetPredecessor sets Node as the successor. This function does not do any
	// validation.
	SetSuccessor(context.Context, *Node) (*MT, error)
	// Notify notifies Chord that Node thinks it is our predecessor. This has
	// the potential to initiate the transferring of keys.
	Notify(context.Context, *Node) (*MT, error)
	// ClosestPrecedingFinger returns the entry of the finger table that
	// precedes ID but is closest to it.
	ClosestPrecedingFinger(context.Context, *ID) (*Node, error)
	// FindSuccessor finds the node the succedes ID. May initiate RPC calls to
	// other nodes.
	FindSuccessor(context.Context, *ID) (*Node, error)
	// Get returns the value in Chord ring for the given key.
	Get(context.Context, *Key) (*Val, error)
	// Put writes a key value pair to the Chord ring.
	Put(context.Context, *KeyVal) (*MT, error)
	// TransferKeys tells a node to transfer keys in a specified range to
	// another node.
	TransferKeys(context.Context, *TransferKeysReq) (*MT, error)
}

func RegisterChordServer(s *grpc.Server, srv ChordServer) {
	s.RegisterService(&_Chord_serviceDesc, srv)
}

func _Chord_GetPredecessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetPredecessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.Chord/GetPredecessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetPredecessor(ctx, req.(*MT))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_GetSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.Chord/GetSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetSuccessor(ctx, req.(*MT))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_SetPredecessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).SetPredecessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.Chord/SetPredecessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).SetPredecessor(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_SetSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).SetSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.Chord/SetSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).SetSuccessor(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.Chord/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).Notify(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_ClosestPrecedingFinger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).ClosestPrecedingFinger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.Chord/ClosestPrecedingFinger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).ClosestPrecedingFinger(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_FindSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).FindSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.Chord/FindSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).FindSuccessor(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.Chord/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyVal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.Chord/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).Put(ctx, req.(*KeyVal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_TransferKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferKeysReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).TransferKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.Chord/TransferKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).TransferKeys(ctx, req.(*TransferKeysReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chord_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gmajpb.Chord",
	HandlerType: (*ChordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPredecessor",
			Handler:    _Chord_GetPredecessor_Handler,
		},
		{
			MethodName: "GetSuccessor",
			Handler:    _Chord_GetSuccessor_Handler,
		},
		{
			MethodName: "SetPredecessor",
			Handler:    _Chord_SetPredecessor_Handler,
		},
		{
			MethodName: "SetSuccessor",
			Handler:    _Chord_SetSuccessor_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _Chord_Notify_Handler,
		},
		{
			MethodName: "ClosestPrecedingFinger",
			Handler:    _Chord_ClosestPrecedingFinger_Handler,
		},
		{
			MethodName: "FindSuccessor",
			Handler:    _Chord_FindSuccessor_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Chord_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Chord_Put_Handler,
		},
		{
			MethodName: "TransferKeys",
			Handler:    _Chord_TransferKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gmaj.proto",
}

func init() { proto.RegisterFile("gmaj.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x92, 0xdd, 0x6a, 0xc2, 0x40,
	0x10, 0x85, 0x49, 0x62, 0x23, 0x8e, 0x69, 0x5a, 0x96, 0x52, 0xc5, 0x9b, 0xda, 0x85, 0x82, 0x95,
	0xe2, 0x85, 0x3e, 0x82, 0xa2, 0x48, 0x50, 0x6c, 0x14, 0x6f, 0x25, 0xba, 0xa3, 0x4d, 0x1b, 0xb3,
	0x76, 0xb3, 0x16, 0xf2, 0x54, 0x7d, 0xc5, 0xb2, 0xf1, 0x87, 0x24, 0xfd, 0xbb, 0xca, 0xd9, 0x9d,
	0x33, 0xdf, 0x9c, 0x2c, 0x03, 0xb0, 0xd9, 0x7a, 0xaf, 0xad, 0x9d, 0xe0, 0x92, 0x13, 0x53, 0xe9,
	0xdd, 0x92, 0x36, 0xa1, 0x30, 0xe6, 0x0c, 0x89, 0x0d, 0xba, 0xcf, 0xaa, 0x5a, 0x5d, 0x6b, 0x58,
	0xae, 0xee, 0x33, 0x42, 0xa0, 0xe0, 0x31, 0x26, 0xaa, 0x7a, 0x5d, 0x6b, 0x94, 0xdc, 0x44, 0xd3,
	0x67, 0xb8, 0x9a, 0x09, 0x2f, 0x8c, 0xd6, 0x28, 0x1c, 0x8c, 0x23, 0x17, 0xdf, 0x49, 0x05, 0x8a,
	0x6b, 0xc1, 0xb7, 0x8b, 0x73, 0xaf, 0xa9, 0x8e, 0x43, 0x46, 0x1e, 0xa0, 0x28, 0xf9, 0x22, 0xe4,
	0x0c, 0x13, 0x44, 0xb9, 0x6d, 0xb5, 0x0e, 0x13, 0x5b, 0x6a, 0x9c, 0x6b, 0x4a, 0xae, 0xbe, 0xb4,
	0x00, 0xfa, 0x68, 0x46, 0x9f, 0xc0, 0x74, 0x30, 0x9e, 0x7b, 0x01, 0xb9, 0x06, 0xe3, 0x0d, 0xe3,
	0x84, 0x55, 0x72, 0x95, 0x54, 0x37, 0x1f, 0x5e, 0x70, 0xcc, 0xa1, 0x24, 0xbd, 0x01, 0x7d, 0xd8,
	0xcb, 0x07, 0xa6, 0x15, 0x30, 0x9c, 0x83, 0x3d, 0x0b, 0x50, 0x85, 0x23, 0x59, 0x71, 0xb4, 0x33,
	0xa7, 0xfd, 0x69, 0xc0, 0x45, 0xf7, 0x85, 0x0b, 0x46, 0x9a, 0x60, 0x0f, 0x50, 0x4e, 0x04, 0x32,
	0x5c, 0x61, 0x14, 0x71, 0x41, 0xe0, 0x94, 0x76, 0x34, 0xab, 0x65, 0x92, 0x93, 0x06, 0x58, 0x03,
	0x94, 0xd3, 0xfd, 0xea, 0x5f, 0x67, 0x13, 0xec, 0x69, 0x96, 0x9a, 0xa9, 0xd7, 0x52, 0x9d, 0x8a,
	0x3a, 0x4d, 0x53, 0x7f, 0x77, 0x52, 0x30, 0xc7, 0x5c, 0xfa, 0xeb, 0xf8, 0x0f, 0x4f, 0x1b, 0x6e,
	0xbb, 0x01, 0x8f, 0x30, 0x52, 0xd3, 0x57, 0xc8, 0xfc, 0x70, 0xd3, 0xf7, 0xc3, 0x0d, 0xa6, 0xd2,
	0x0e, 0x7b, 0xb9, 0xb4, 0x8f, 0x70, 0xd9, 0xf7, 0x43, 0xf6, 0xc3, 0x8f, 0x7d, 0xb3, 0xde, 0x81,
	0x31, 0x40, 0x49, 0xca, 0xa7, 0x4b, 0x07, 0xe3, 0xda, 0xf9, 0xa0, 0xde, 0xfa, 0x1e, 0x8c, 0xc9,
	0x5e, 0x12, 0x3b, 0x65, 0x98, 0x7b, 0x41, 0x26, 0x62, 0x07, 0xac, 0xf4, 0x2e, 0x91, 0xca, 0xa9,
	0x96, 0xdb, 0xb0, 0x74, 0xd3, 0xd2, 0x4c, 0x76, 0xb7, 0xf3, 0x15, 0x00, 0x00, 0xff, 0xff, 0x7c,
	0xe0, 0x90, 0xb4, 0xc9, 0x02, 0x00, 0x00,
}
