// Code generated by protoc-gen-go.
// source: github.com/r-medina/gmaj/gmajpb/gmaj.proto
// DO NOT EDIT!

/*
Package gmajpb is a generated protocol buffer package.

It is generated from these files:
	github.com/r-medina/gmaj/gmajpb/gmaj.proto

It has these top-level messages:
	Node
	GetIDRequest
	GetIDResponse
	LocateRequest
	LocateResponse
	GetRequest
	GetResponse
	PutRequest
	PutResponse
	TransferKeysReq
	MT
	KeyVal
	ID
	Key
	Val
*/
package gmajpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Node contains a node ID and address.
type Node struct {
	Id   []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr" json:"addr,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Node) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Node) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type GetIDRequest struct {
}

func (m *GetIDRequest) Reset()                    { *m = GetIDRequest{} }
func (m *GetIDRequest) String() string            { return proto.CompactTextString(m) }
func (*GetIDRequest) ProtoMessage()               {}
func (*GetIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetIDResponse struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *GetIDResponse) Reset()                    { *m = GetIDResponse{} }
func (m *GetIDResponse) String() string            { return proto.CompactTextString(m) }
func (*GetIDResponse) ProtoMessage()               {}
func (*GetIDResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetIDResponse) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type LocateRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *LocateRequest) Reset()                    { *m = LocateRequest{} }
func (m *LocateRequest) String() string            { return proto.CompactTextString(m) }
func (*LocateRequest) ProtoMessage()               {}
func (*LocateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LocateRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type LocateResponse struct {
	Node *Node `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
}

func (m *LocateResponse) Reset()                    { *m = LocateResponse{} }
func (m *LocateResponse) String() string            { return proto.CompactTextString(m) }
func (*LocateResponse) ProtoMessage()               {}
func (*LocateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LocateResponse) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type GetRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResponse struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutRequest struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutResponse struct {
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type TransferKeysReq struct {
	FromId []byte `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToNode *Node  `protobuf:"bytes,2,opt,name=to_node,json=toNode" json:"to_node,omitempty"`
}

func (m *TransferKeysReq) Reset()                    { *m = TransferKeysReq{} }
func (m *TransferKeysReq) String() string            { return proto.CompactTextString(m) }
func (*TransferKeysReq) ProtoMessage()               {}
func (*TransferKeysReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *TransferKeysReq) GetFromId() []byte {
	if m != nil {
		return m.FromId
	}
	return nil
}

func (m *TransferKeysReq) GetToNode() *Node {
	if m != nil {
		return m.ToNode
	}
	return nil
}

type MT struct {
}

func (m *MT) Reset()                    { *m = MT{} }
func (m *MT) String() string            { return proto.CompactTextString(m) }
func (*MT) ProtoMessage()               {}
func (*MT) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type KeyVal struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val []byte `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (m *KeyVal) Reset()                    { *m = KeyVal{} }
func (m *KeyVal) String() string            { return proto.CompactTextString(m) }
func (*KeyVal) ProtoMessage()               {}
func (*KeyVal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *KeyVal) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyVal) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type ID struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *ID) Reset()                    { *m = ID{} }
func (m *ID) String() string            { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()               {}
func (*ID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ID) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type Key struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Key) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Val struct {
	Val []byte `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (m *Val) Reset()                    { *m = Val{} }
func (m *Val) String() string            { return proto.CompactTextString(m) }
func (*Val) ProtoMessage()               {}
func (*Val) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Val) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "gmajpb.Node")
	proto.RegisterType((*GetIDRequest)(nil), "gmajpb.GetIDRequest")
	proto.RegisterType((*GetIDResponse)(nil), "gmajpb.GetIDResponse")
	proto.RegisterType((*LocateRequest)(nil), "gmajpb.LocateRequest")
	proto.RegisterType((*LocateResponse)(nil), "gmajpb.LocateResponse")
	proto.RegisterType((*GetRequest)(nil), "gmajpb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "gmajpb.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "gmajpb.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "gmajpb.PutResponse")
	proto.RegisterType((*TransferKeysReq)(nil), "gmajpb.TransferKeysReq")
	proto.RegisterType((*MT)(nil), "gmajpb.MT")
	proto.RegisterType((*KeyVal)(nil), "gmajpb.KeyVal")
	proto.RegisterType((*ID)(nil), "gmajpb.ID")
	proto.RegisterType((*Key)(nil), "gmajpb.Key")
	proto.RegisterType((*Val)(nil), "gmajpb.Val")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GMaj service

type GMajClient interface {
	// GetID returns the ID of the node.
	GetID(ctx context.Context, in *GetIDRequest, opts ...grpc.CallOption) (*GetIDResponse, error)
	// Locate finds where a key belongs.
	Locate(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error)
	// Get returns the value in Chord ring for the given key.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// Put writes a key value pair to the Chord ring.
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
}

type gMajClient struct {
	cc *grpc.ClientConn
}

func NewGMajClient(cc *grpc.ClientConn) GMajClient {
	return &gMajClient{cc}
}

func (c *gMajClient) GetID(ctx context.Context, in *GetIDRequest, opts ...grpc.CallOption) (*GetIDResponse, error) {
	out := new(GetIDResponse)
	err := grpc.Invoke(ctx, "/gmajpb.GMaj/GetID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gMajClient) Locate(ctx context.Context, in *LocateRequest, opts ...grpc.CallOption) (*LocateResponse, error) {
	out := new(LocateResponse)
	err := grpc.Invoke(ctx, "/gmajpb.GMaj/Locate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gMajClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/gmajpb.GMaj/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gMajClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/gmajpb.GMaj/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GMaj service

type GMajServer interface {
	// GetID returns the ID of the node.
	GetID(context.Context, *GetIDRequest) (*GetIDResponse, error)
	// Locate finds where a key belongs.
	Locate(context.Context, *LocateRequest) (*LocateResponse, error)
	// Get returns the value in Chord ring for the given key.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// Put writes a key value pair to the Chord ring.
	Put(context.Context, *PutRequest) (*PutResponse, error)
}

func RegisterGMajServer(s *grpc.Server, srv GMajServer) {
	s.RegisterService(&_GMaj_serviceDesc, srv)
}

func _GMaj_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMajServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.GMaj/GetID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMajServer).GetID(ctx, req.(*GetIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GMaj_Locate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMajServer).Locate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.GMaj/Locate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMajServer).Locate(ctx, req.(*LocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GMaj_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMajServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.GMaj/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMajServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GMaj_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GMajServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gmajpb.GMaj/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GMajServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GMaj_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gmajpb.GMaj",
	HandlerType: (*GMajServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetID",
			Handler:    _GMaj_GetID_Handler,
		},
		{
			MethodName: "Locate",
			Handler:    _GMaj_Locate_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GMaj_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _GMaj_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/r-medina/gmaj/gmajpb/gmaj.proto",
}

func init() { proto.RegisterFile("github.com/r-medina/gmaj/gmajpb/gmaj.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0x6d, 0xcb, 0xda, 0x30,
	0x14, 0xa5, 0x2f, 0x56, 0xbc, 0xbe, 0x4c, 0x32, 0x37, 0xc5, 0x0f, 0x9b, 0xcb, 0x18, 0x88, 0x6c,
	0x15, 0x9c, 0xb0, 0x3f, 0x20, 0x14, 0x71, 0x0e, 0x57, 0x64, 0x5f, 0x25, 0x9a, 0xe8, 0xea, 0x63,
	0x1b, 0x6d, 0x53, 0xc1, 0x1f, 0xfa, 0xfc, 0x9f, 0x87, 0xa6, 0xd1, 0xd6, 0xb7, 0x2f, 0xcd, 0xbd,
	0x37, 0xe7, 0x1c, 0x4e, 0xee, 0x29, 0xf4, 0x36, 0x9e, 0xf8, 0x1f, 0x2f, 0xed, 0x15, 0xf7, 0xfb,
	0xe1, 0x0f, 0x9f, 0x51, 0x2f, 0x20, 0xfd, 0x8d, 0x4f, 0xb6, 0xf2, 0xb3, 0x5f, 0xca, 0xc3, 0xde,
	0x87, 0x5c, 0x70, 0x64, 0xa5, 0x23, 0xdc, 0x03, 0xf3, 0x0f, 0xa7, 0x0c, 0xd5, 0x40, 0xf7, 0x68,
	0x4b, 0xeb, 0x68, 0xdd, 0x8a, 0xab, 0x7b, 0x14, 0x21, 0x30, 0x09, 0xa5, 0x61, 0x4b, 0xef, 0x68,
	0xdd, 0x92, 0x2b, 0x6b, 0x5c, 0x83, 0x8a, 0xc3, 0xc4, 0x78, 0xe4, 0xb2, 0x43, 0xcc, 0x22, 0x81,
	0x3f, 0x43, 0x55, 0xf5, 0xd1, 0x9e, 0x07, 0xd1, 0x9d, 0x08, 0xfe, 0x02, 0xd5, 0xdf, 0x7c, 0x45,
	0x04, 0x53, 0x0c, 0x54, 0x07, 0xe3, 0x85, 0x9d, 0x24, 0xa2, 0xe4, 0x26, 0x25, 0x1e, 0x40, 0xed,
	0x0c, 0x51, 0x22, 0x1d, 0x30, 0x03, 0x4e, 0x99, 0x04, 0x95, 0x07, 0x15, 0x3b, 0x35, 0x6a, 0x27,
	0x2e, 0x5d, 0x79, 0x83, 0x3f, 0x01, 0x38, 0x4c, 0x3c, 0xd7, 0xfc, 0x0a, 0x65, 0x79, 0xaf, 0x04,
	0x1b, 0x50, 0x38, 0x92, 0x5d, 0xcc, 0x94, 0xb1, 0xb4, 0xc1, 0x43, 0x80, 0x59, 0xfc, 0x5c, 0x24,
	0x63, 0xe9, 0x79, 0x56, 0x15, 0xca, 0x92, 0x95, 0x4a, 0xe3, 0xbf, 0xf0, 0x6e, 0x1e, 0x92, 0x20,
	0x5a, 0xb3, 0x70, 0xc2, 0x4e, 0x91, 0xcb, 0x0e, 0xa8, 0x09, 0xc5, 0x75, 0xc8, 0xfd, 0xc5, 0x65,
	0x11, 0x56, 0xd2, 0x8e, 0x29, 0xfa, 0x06, 0x45, 0xc1, 0x17, 0xf2, 0x69, 0xfa, 0x83, 0xa7, 0x59,
	0x82, 0x27, 0x27, 0x36, 0x41, 0x9f, 0xce, 0xf1, 0x77, 0xb0, 0x26, 0xec, 0xf4, 0x8f, 0xec, 0x1e,
	0x38, 0xab, 0x83, 0x71, 0x24, 0x3b, 0xe5, 0x2b, 0x29, 0x71, 0x03, 0xf4, 0xf1, 0xe8, 0x6e, 0xfb,
	0x4d, 0x30, 0x26, 0x29, 0xfc, 0x66, 0x3f, 0x4d, 0x30, 0x94, 0x72, 0xa2, 0xa3, 0x5d, 0x74, 0x06,
	0xaf, 0x1a, 0x98, 0xce, 0x94, 0x6c, 0xd1, 0x10, 0x0a, 0x32, 0x59, 0xd4, 0x38, 0x7b, 0xcc, 0x07,
	0xdf, 0xfe, 0x70, 0x33, 0x55, 0x8b, 0xfe, 0x05, 0x56, 0x9a, 0x25, 0xba, 0x00, 0xae, 0xe2, 0x6f,
	0x7f, 0xbc, 0x1d, 0x2b, 0xa2, 0x0d, 0x86, 0xc3, 0x04, 0x42, 0x39, 0xd9, 0x33, 0xe5, 0xfd, 0xd5,
	0x2c, 0xc3, 0xcf, 0xe2, 0x1c, 0x3e, 0x0b, 0x32, 0xc3, 0xe7, 0x62, 0x5a, 0x5a, 0xf2, 0x9f, 0xff,
	0xf9, 0x16, 0x00, 0x00, 0xff, 0xff, 0x38, 0xf7, 0x6b, 0x18, 0x21, 0x03, 0x00, 0x00,
}
